spring:
    application:
        name: project1
    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: jdbc:postgresql://localhost:5432/regulatory_manager
        username: postgres
        password: AnvilofWar231!
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
